#!/bin/bash

# set the location of the vdf file
# 	if no args given: use default location
# 	else: assume argument is user specified vdf location
# if the vdf exists, use awk to extract path values from vdf
# else: show warning to user and exit
# set bash IFS value to newline
# 	bash tokenises using the IFS variable (defaulting to space)
# 	this breaks if a steam library has a space in it
# 	using an alternate value fixed the issue
# generate a tmpfile to save game data
# for every detected library:
# 	for every appmanifest file in library:
# 		extract the app name and id, then save in the tmpfile
# sort the tmpfile to alphabetise the games
# cat the tmpfile into wmenu to prompt the user to select a game
# extract the game id from the user selection
# run the game through steam

# set defaults
launcher="wmenu"
vdf="${HOME}/.steam/steam/steamapps/libraryfolders.vdf"

# process args
OPTIND=1

while getopts ":v:l:": opt; do
	case $opt in
		l) launcher=$OPTARG ;;
		v) vdf=$OPTARG ;;
	esac
done

# with quotes as the delimiter, the full path to each steam library will be the 4th column
if [ -e $vdf ]; then
	libs=$(awk -F'"' '/"path"/ { print $4 }' $vdf)
else
	echo "unable to read $vdf - file does not exist"
	exit 1
fi

## process the app manifest files
IFSNORMAL=$IFS
IFSNEWLINE=$(echo -en "\n\b")
IFS=$IFSNEWLINE

tmpfile=$(mktemp)
for lib in $libs; do
	for file in $lib/steamapps/*.acf; do
		appid=$(awk -F'"' '/"appid"/ { print $4 }' $file)
		name=$(awk -F'"' '/"name"/ { print tolower($4) }' $file)
		echo $name::$appid >> $tmpfile 
	done
done

## prompt the user to pick a game via wmenu
sort -o $tmpfile $tmpfile
game=$(cat $tmpfile | $launcher)

if [[ -z $game ]]; then exit 2; fi
## extract game id from user selection and run
selection=$(echo $game | awk -F'::' '{ print $2 }')
rm $tmpfile
steam steam://rungameid/$selection
